services:
  backend:
    image: wildcodehub/dev-server-backend:latest
    ports:
      - 4001:4000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  frontend:
    command: sh -c "npm run build && npm run start"
    image: wildcodehub/dev-server-frontend:latest
    ports:
      - 3001:3000
    env_file:
      - ./.env
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_IMAGE_URL=http://localhost:8000
  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_DB} -U ${USERNAME_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./.env
    ports:
      - 5434:5432
    volumes:
      - wildcodehub-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21.3
    depends_on:
     - frontend
     - backend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

volumes:
  wildcodehub-data:
  wildcodehub-data-test:
