services:
  backend-dev:
    image: wildcodehub/dev-server-backend:latest
    ports:
      - 4000:4000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    depends_on:
      db-dev:
        condition: service_healthy
    env_file:
      - ./.env
  frontend-dev:
    command: sh -c "npm run build && npm run start"
    image: wildcodehub/dev-server-frontend:latest
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_IMAGE_URL=http://localhost:8000
  db-dev:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildcodehub -U root"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5433:5432
    volumes:
      - wildcodehub-data:/var/lib/postgresql/data

  nginx-dev:
    image: nginx:1.21.3
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx-dev.conf
      - ./logs:/var/log/nginx-dev

volumes:
  wildcodehub-data:
  wildcodehub-data-test: