name: test backend

on: push

jobs:
  test:
    name: 🔧 Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v4
      - name: ⬇️ Installation des dépendances
        run: npm install
      - name: 🚀 Lancement des tests
        run: npm run test:ci

  build-image:
    needs: test
    name: 🐋 Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{secrets.DOCKERHUB_USERNAME}}/dev:latest
