name: Tests

on: push

jobs:
  test-backend:
    name: 🔧 Test
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: wildcodehub-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5434:5432

    defaults:
      run:
        working-directory: backend
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v4
      - name: ⬇️ Installation des dépendances
        run: npm install
      - name: 🚀 Lancement des tests
        run: npm run test:ci

  build-image-backend:
    needs: [test-backend]
    name: 🐋 Docker build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v2
      name: Set up Docker Buildx
    - name: Build the Docker image
      run: docker build -f ./backend/Dockerfile
